model:
  use_residual_decoder: true
  use_history_in_ode: true
  use_relative_time: true
  relative_time_mode: normalized
  history_encoder:
    history_encoder_type: transformer
    use_transformer_history: true
    history_use_positional_encoding: true
